name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  App_CI:
    uses: ./.github/workflows/app-ci.yml

  API_CI:
    uses: ./.github/workflows/api-ci.yml

  App_CD:
    needs: [App_CI, API_CI]
    uses: ./.github/workflows/app-cd.yml
    secrets: inherit

  API_CD:
    needs: [App_CI, API_CI]
    uses: ./.github/workflows/api-cd.yml
    secrets: inherit
