# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  workflow_dispatch
  push:
    branches: [ "main" ]

jobs:

  App:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src/app

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/app/package-lock.json

    - name: Checkout
      uses: actions/checkout@v3

    - name: NPM Install
      run: npm ci

    - name: NPM Build
      run: npm run build --if-present

    - name: NPM Test
      run: npm test

  API:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/api

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: .NET Restore
      run: dotnet restore

    - name: .NET Build
      run: dotnet build --no-restore

    - name: .NET Test
      run: dotnet test --no-build --verbosity normal
