name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]

jobs:

  App_CI:
    uses: ./.github/workflows/app-ci.yml

  API_CI:
    uses: ./.github/workflows/api-ci.yml
